# Generated by Django 5.2 on 2025-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='point1',
            field=models.FloatField(default=3.1),
        ),
        migrations.AlterField(
            model_name='direction',
            name='point2',
            field=models.FloatField(default=2.1),
        ),
        migrations.AlterField(
            model_name='direction',
            name='point3',
            field=models.FloatField(default=1.1),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
