# Generated by Django 5.2 on 2025-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_direction_point1_alter_direction_point2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='maximum_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
